### ISSUE TITLE
Add standalone running funcionality

### ISSUE THREAD

**Issue by mjlescano** [DemocracyOS/notifier#1]

**Comment by gvilarino** [comment]
This isn't a responsibility of `notifier` but of `notifier-server`

**Comment by sachalifs** [comment]
?

@gvilarino wasn't `notifier-server` deprecated?

**Comment by gvilarino** [comment]
Not at all, it's just not up-to-date yet.

I'll try to be clear about how this is to be played out:
- `notifier` (this repo) is a node module that relies on MongoDB to handle events generated by `DemocracyOS` users and process notifications based on those events. It is independant of how/where its client runs.
- [`notifier-server`](DemocracyOS/notifier-server) is a webserver that _currenty_ provides full notifications functionality (pre `1.0.0`) and is intended to provide (as from `1.0.0`) a webserver that just wraps `notifier`. From the outside it will look like its current implementation, with the difference that event handling will be defined in `notifier` and not the `notifier-server` repo.
- [`DemocracyOS`](DemocracyOS/app) may run `notifier` embedded for single server deployments or rely on an external `notifier-server` (that wraps a `notifier`) to handle and process its notifications.

3 repos

**Comment by sachalifs** [comment]
ok then we'll move this issue to [`notifier-server`](https://github.com/DemocracyOS/notifier-server)

**Comment by gvilarino** [comment]
Awesome. Keep in mind everything related to this is to be developed under the [`1.0.0`](https://github.com/DemocracyOS/notifier-server/tree/1.0.0) branch, just kike in `notifier` and [`DemocracyOS`](DemocracyOS/app)
