### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/notifier#13]
We don't need to rely on `DemocracyOS/democracyos` to test this app.

**Comment by SebastienDaniel** [comment]
I can cover this.

Does the DemocracyOS team have a preference?
I usually go with mocha/chai (expect) / sinon

**Comment by mjlescano** [comment]
Awesome @SebastienDaniel !

What do you think about the [code](https://github.com/DemocracyOS/notifier/commit/bac13a02fc0cf9dedc6c47b154e28216bf775237) already pushed by @jfresco? Can you continue from there?

**Comment by SebastienDaniel** [comment]
ha, that's perfect, very comfortable with that.

I'll take it from there, thx for the link @mjlescano

**Comment by SebastienDaniel** [comment]
The timing module `lib/utils/timing.js` exposes some of its implementation details via the `finish()` method. It does so by returning a `moment.js` duration object.

I don't know where the timing module is used, but shouldn't it instead return something more generic, like milliseconds?

**Comment by gvilarino** [comment]
Yeah, probably. I'm not that sure about it either. I guess it's something `mocha` relies on to display stuff? Maybe @jfresco can shed some light here.

**Comment by jfresco** [comment]
@SebastienDaniel [Here](https://github.com/DemocracyOS/notifier/blob/master/index.js#L57-L65) is where `timing` is being used.
Exposing `moment` seems unnecessary -- in fact, **using** `moment` seems unnecessary. Perhaps the `timing` module can be reimplemented using just the `Date` functions.
Anyway, is not a fix to be done in the scope of this issue.

**Comment by gvilarino** [comment]
Agree with @jfresco; mostly how the notifier tracks how much time a task takes, for logging. We could disable this in `production` if necessary, or through a config setting. However I'm not entirely sure how this is bothering with the tests.

**Comment by SebastienDaniel** [comment]
@jfresco thx!

@gvilarino It's not bothering with testing itself, I just wanted to flag a potential improvement for the timing module.

**Comment by gvilarino** [comment]
Cool! Care to open a separate issue so we can discuss there?
