### ISSUE TITLE
Allow `notifier` to be called more than once

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/notifier#15]
``` js
var notifier = require('democracyos-notifier')
notifier({}, function () {})
notifier({}, function () {}) // <-- crashes
```

That's because the first call mutates the `notifier` object. The signature of the object should remain equal. It's expected `notifier` to be a singleton.

**Comment by gvilarino** [comment]
The behavior is just as with `express` or `page`. `notifier` IS a singleton but it _must_ be initialized.

Any further calls to `notifier` after initialization are idempotent.
