### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by kvdmolen** [DemocracyOS/notifier#2]
Hello, how do I start this server?

```
node index.js
```

does not work: `Error: Cannot find module '../build/Release/bson']`

Please update the readme!

**Comment by gvilarino** [comment]
@kvdmolen this is a node module, it's not supposed to be started. Go check [`notifier-server`](DemocracyOS/notifier-server) for a standalone implementation.

**Comment by kvdmolen** [comment]
Ok, but in the intallation-guide, it states:

`Install, Config and run the Notifier Server.`

How should i do that?
The `notifier-server` does not appear in the packages.json...

**Comment by gvilarino** [comment]
Yeah, sorry, done: https://github.com/DemocracyOS/app/wiki/Notifications
