### ISSUE TITLE
name property causing confusion

### ISSUE THREAD

**Issue by asbjornenge** [DemocracyOS/notifier#20]
Hi! 

I've been struggling setting up notifications for my democracyos instance. It seems the `notifications.mailer.name` property leaks through to `nodemailer` -> `options.name optional hostname of the client, used for identifying to the server` which is causing weird behaviour when set to something other than `localhost`.

I had the same issue with both `gmail` and `mailgun` services.

If I set the `name` property to `localhost` in democracyos `config.json` things start working, but then the `from` field also is set to `localhost` which is the sad part :stuck_out_tongue_closed_eyes:

**Comment by asbjornenge** [comment]
I also need to modify other options passed to `nodemailer`. Specifically the `port`. Would be great if there were a way to pass `nodemailer` options via democracyos `config.json` :smile:

**Comment by gvilarino** [comment]
Weird indeed.

Could you share your config file (hiding any private keys)?

**Comment by asbjornenge** [comment]
Sure. I'll share my notifications section, do you need to see anything else?

```
  "notifications": {
    "url": "",
    "token": "",
    "mailer": {
      "name": "My Awesome Site",
      "email": "no-reply@<domain>",
      "service": "mailgun",
      "auth": {
        "user": "no-reply@<domain>",
        "pass": "<somepass>"
      }
    }
  },
```

I'm running a fork of the `democracyos-notifier` (this repo) with a modified `createTransport` that looks like this:

```
function createTransport(config) {
  log('Initializing nodemailer API client')
  var opts = config && config.service ? config : undefined
  opts.name = 'localhost'
  opts.port = 2525
  return nodemailer.createTransport(opts)
}
```

Would be cool to be able to control these `opts` (passed to nodemailer) from the main `config.json` :smile:

**Comment by gvilarino** [comment]
That's great for the time being. I agree, it'd be awesome being able to control the whole notifier from the main config, but this was designed so `DemocracyOS` and `notifier` can:
1. scale each process/app independently
2. your `notifier` separate instance may process events from multiple `DemocracyOS` deployments, as well as external, third party events, without needing to modify `DemocracyOS` itself.

We've seen usage of 1 ourselves, and 2 from some users. For instance, some organisation in Ukraine had to provide different instances, one in Russian the other in Ukrainian, with different settings, under different domains, but they wanted to share the user database, so you could log into either app with the same credentials.

**Comment by asbjornenge** [comment]
I still think it's a bit confusing. Most people trying out `DemocracyOs` for the first time are going to use the `builtin notifier`, so imho it's a good idea to have a clear path for that. My guess is that this issue will hit many trying to deploy and cause people to give up / prevent adoption.

Also, I don't see how adding something like this:

```
  "notifications": {
    "url": "",
    "token": "",
    "mailer": {
      "name": "My Awesome Site",
      "email": "no-reply@<domain>",
      "service": "mailgun",
      "auth": {
        "user": "no-reply@<domain>",
        "pass": "<somepass>"
      },
      "nodemailer": { // <- NEW!
        "name": "localhost",
        "port": 2525
      }
    }
  }
```

will cause any trouble for deploying a separate `notifier` instance? Once you need that, you are also willing to dig in a bit more. Maybe it's also a good idea to change the `name` property under `mailer` to something a bit more appropriate like `fromName` or something like that? 

:smile:

**Comment by mjlescano** [comment]
We'll be adding DemocracyOS/config and make sure this works properly and clearly :)

**Comment by mjlescano** [comment]
A `nodemailer: {}` config is available, also using the embedded version 😊
