### ISSUE TITLE
Parametrize sender mail & name

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/notifier#3]
As per https://github.com/DemocracyOS/notifier-server/issues/38

I think `notifier` should _not_ define this since [it's already handling it in the mail transport](https://github.com/DemocracyOS/notifier/blob/development/lib/transports/index.js#L17), **but** there's no built-in API for reading/receiving this from the host application (either [`DemocracyOS`](DemocracyOS/app) or [`notifier-server`](DemocracyOS/notifier-server)).

Organization name and organization 'from email' should be passed to `notifier` when calling the `start` function as part of the `opts`. Like:

``` json
{
  agenda: { /*agenda obj*/ },
  from: {
    email: "no-reply@democracyos.org",
    name: "The DemocracyOS team"
  }
}
```

Then, [`DemocracyOS`](DemocracyOS/app) and [`notifier-server`](DemocracyOS/notifier-server) should be aware of their configurations for sending the appropriate params to their `notifier` instance.

**Comment by gvilarino** [comment]
@slifszyc I just update the issue description so it's clearer

**Comment by mjlescano** [comment]
This is already implemented :)
